services:
  production:
    container_name: kitchen-app-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    profiles:
      - production

  db:
    image: postgres:17-alpine
    container_name: kitchen-app-db
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: kitchen-app-pgadmin4
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  db_data:
